spring.application.name=Book_Partner_Portal
server.port=8086
spring.datasource.url=jdbc:mysql://10.10.164.153:3306/pubs
spring.datasource.username=deepu
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

